# Generated by Django 5.1.2 on 2024-10-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='delete',
        ),
    ]
