# Generated by Django 5.1.2 on 2024-10-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_category_todo_tags_alter_todo_details_todo_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date']},
        ),
    ]
